import type { RuleDefinition } from "../types";

export const defaultRules = [
  {
    id: "must-ai-study-30m",
    name: "学习 30 分钟",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 6,
    enabledByDefault: true,
  },
  {
    id: "must-plank",
    name: "平板支撑 3 x 30s",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "must-wall-sit",
    name: "靠墙静蹲 3 x 30s",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "must-squat",
    name: "深蹲 3 x 15",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "must-standing-pushup",
    name: "站姿俯卧撑 3 组",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "must-meditation-5m",
    name: "冥想 5 分钟",
    kind: "must",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 3,
    enabledByDefault: true,
  },
  {
    id: "bonus-ai-study-60m",
    name: "学习达到 60 分钟",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 4,
    enabledByDefault: true,
  },
  {
    id: "bonus-ai-study-90m",
    name: "学习达到 90 分钟",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 3,
    enabledByDefault: true,
  },
  {
    id: "bonus-swim-1km",
    name: "游泳 1 公里",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 10,
    enabledByDefault: true,
  },
  {
    id: "bonus-healthy-meal",
    name: "主动健康饮食",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "bonus-evening-family-focus",
    name: "晚间 30 分钟不碰手机陪家人",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 3,
    enabledByDefault: true,
  },
  {
    id: "bonus-emotion-review",
    name: "主动情绪复盘 5 分钟",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "bonus-extra-housework",
    name: "额外完成一项家务",
    kind: "bonus",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 2,
    enabledByDefault: true,
  },
  {
    id: "vice-late-sleep",
    name: "熬夜",
    kind: "vice",
    direction: "loss",
    riskStatus: "danger",
    unit: "time-slot",
    enabledByDefault: true,
    steps: [
      { threshold: 2230, score: -2, label: "22:30-22:59" },
      { threshold: 2300, score: -4, label: "23:00-23:29" },
      { threshold: 2330, score: -6, label: "23:30-23:59" },
      { threshold: 2400, score: -9, label: "00:00-00:29" },
      { threshold: 2430, score: -13, label: "00:30-00:59" },
      { threshold: 2500, score: -18, label: "01:00+" },
    ],
  },
  {
    id: "vice-game-overtime",
    name: "游戏超时",
    kind: "vice",
    direction: "loss",
    riskStatus: "warning",
    unit: "minute",
    enabledByDefault: true,
    steps: [
      { threshold: 30, score: 0, label: "<=30 分钟" },
      { threshold: 60, score: -2, label: "30-60 分钟" },
      { threshold: 120, score: -5, label: "1-2 小时" },
      { threshold: 240, score: -9, label: "2-4 小时" },
      { threshold: 241, score: -15, label: "4 小时以上" },
    ],
  },
  {
    id: "vice-junk-food",
    name: "垃圾食品",
    kind: "vice",
    direction: "loss",
    riskStatus: "warning",
    unit: "count",
    enabledByDefault: true,
    steps: [
      { threshold: 1, score: -3, label: "薯片 1 包" },
      { threshold: 2, score: -5, label: "汉堡 1 个" },
      { threshold: 3, score: -5, label: "炸鸡 1 份" },
      { threshold: 4, score: -4, label: "含糖饮料 1 杯" },
      { threshold: 5, score: -2, label: "深夜额外加罚" },
    ],
  },
  {
    id: "vice-mobile-game-spend",
    name: "手游氪金",
    kind: "vice",
    direction: "loss",
    riskStatus: "danger",
    unit: "money",
    enabledByDefault: true,
    steps: [
      { threshold: 30, score: -3, label: "1-30 元" },
      { threshold: 98, score: -6, label: "31-98 元" },
      { threshold: 198, score: -10, label: "99-198 元" },
      { threshold: 199, score: -16, label: "198 元以上" },
    ],
  },
  {
    id: "vice-phone-scroll",
    name: "刷手机超时",
    kind: "vice",
    direction: "loss",
    riskStatus: "warning",
    unit: "minute",
    enabledByDefault: true,
    steps: [
      { threshold: 30, score: -2, label: "30 分钟以上" },
      { threshold: 60, score: -5, label: "60 分钟以上" },
      { threshold: 90, score: -8, label: "90 分钟以上" },
    ],
  },
  {
    id: "vice-oil-burst-forced",
    name: "油冲未兑换强行发生",
    kind: "vice",
    direction: "loss",
    riskStatus: "danger",
    unit: "count",
    score: -50,
    enabledByDefault: true,
    privateLabel: true,
  },
  {
    id: "vice-family-emotion",
    name: "家庭情绪失守",
    kind: "vice",
    direction: "loss",
    riskStatus: "warning",
    unit: "count",
    score: -4,
    enabledByDefault: true,
  },
  {
    id: "family-task-basic",
    name: "家务完成 1 项",
    kind: "family-task",
    direction: "gain",
    riskStatus: "safe",
    unit: "count",
    score: 3,
    dailyCap: 2,
    enabledByDefault: true,
  },
  {
    id: "family-companion-10m",
    name: "陪伴家人 10 分钟",
    kind: "family-companion",
    direction: "gain",
    riskStatus: "safe",
    unit: "minute",
    score: 4,
    dailyCap: 2,
    enabledByDefault: true,
  },
  {
    id: "redeem-game-30m",
    name: "游戏 30 分钟",
    kind: "redeem",
    direction: "spend",
    riskStatus: "warning",
    unit: "minute",
    score: 6,
    enabledByDefault: true,
  },
  {
    id: "redeem-game-1h",
    name: "游戏 1 小时",
    kind: "redeem",
    direction: "spend",
    riskStatus: "warning",
    unit: "minute",
    score: 10,
    enabledByDefault: true,
  },
  {
    id: "redeem-snack-10",
    name: "零食额度 10 元",
    kind: "redeem",
    direction: "spend",
    riskStatus: "warning",
    unit: "money",
    score: 8,
    enabledByDefault: true,
  },
  {
    id: "redeem-snack-20",
    name: "零食额度 20 元",
    kind: "redeem",
    direction: "spend",
    riskStatus: "warning",
    unit: "money",
    score: 15,
    enabledByDefault: true,
  },
  {
    id: "redeem-mobile-game-30",
    name: "手游氪金额度 30 元",
    kind: "redeem",
    direction: "spend",
    riskStatus: "danger",
    unit: "money",
    score: 22,
    enabledByDefault: true,
  },
  {
    id: "redeem-figure-blindbox-50",
    name: "手办/盲盒额度 50 元",
    kind: "redeem",
    direction: "spend",
    riskStatus: "danger",
    unit: "money",
    score: 35,
    enabledByDefault: true,
  },
  {
    id: "redeem-oil-burst",
    name: "油冲 1 次",
    kind: "redeem",
    direction: "spend",
    riskStatus: "danger",
    unit: "count",
    score: 35,
    cooldownDays: 3,
    enabledByDefault: true,
    privateLabel: true,
  },
  {
    id: "redeem-shopping-50",
    name: "购物额度 50 元",
    kind: "redeem",
    direction: "spend",
    riskStatus: "warning",
    unit: "money",
    score: 30,
    enabledByDefault: true,
  },
] as const satisfies readonly RuleDefinition[];
